# Personal machine extras (karmapolice, streetspirit).
# Merged with the common homebrew config in ../../darwin/homebrew.nix.
{ ... }: {
  homebrew.casks = [
    "aldente"
    "autodesk-fusion"
    "bartender"
    "blender"
    "beeper"
    "crossover"
    "discord"
    "dropbox"
    "godot"
    "google-chrome"
    "linear"
    "megasync"
    "notion"
    "obs"
    "obsidian"
    "openemu"
    "plex"
    "plexamp"
    "proton-drive"
    "proton-mail"
    "proton-mail-bridge"
    "protonvpn"
    "rancher"
    "scrivener"
    "steam"
    "tidal"
    "transmission-remote-gui"
    "vlc"
    "zen"
    "zoom"
  ];
}
