{ pkgs, vars, config, ... }: {
  programs.zsh = {
    enable = true;

    enableCompletion = true;
    # autosuggestion = {
    #   enable = true;
    # };
    #shellAliases = import ../bash/aliases.nix;
    shellAliases = {
      l = "ls -Glah";
      nixswitch = "darwin-rebuild switch --flake ~/.dotfiles#$(hostname -s)";
      nixup = "pushd ~/.dotfiles; nix flake update; nixswitch; popd";
      sbtc = "sbt --client";
    };
    history = {
      ignoreDups = true;
      share = true;
      save = 100000;
    };

    oh-my-zsh = {
      enable = true;
      plugins = [ "dircycle" "zsh-navigation-tools" "ssh-agent" "z" ];
      /* ugly hack: oh my zsh only wants a relative path, so lets go back to the system root */
      #theme = "robbyrussell";
      #theme = "../../../../../../../../../../../${pkgs.zsh-powerlevel9k}/share/zsh-powerlevel9k/powerlevel9k";
      extraConfig = ''
        zstyle :omz:plugins:ssh-agent identities id_ed25519
        zstyle :omz:plugins:ssh-agent helper macos-keychain
      '';
    };

    sessionVariables = config.home.sessionVariables;

    initExtra = ''
      # Load secrets as environment variables
      [ -r "${config.sops.secrets.localstack_auth_token.path}" ] && export LOCALSTACK_AUTH_TOKEN="$(cat ${config.sops.secrets.localstack_auth_token.path})"
      [ -r "${config.sops.secrets.ghe_token.path}" ] && export GITHUB_API_TOKEN="$(cat ${config.sops.secrets.ghe_token.path})"

      export PATH="$HOME/scripts:$HOME/bin:/opt/local/bin:/usr/local/bin:/Users/wrose/Library/Application Support/Coursier/bin:/bin:/usr/bin:/run/current-system/sw/bin:$HOME/.sxm/bin"


      # set TERMINFO to the terminfos delivered by the ncurses nix package
      if [ ! -f /etc/NIXOS ]; then
        export TERMINFO=$HOME/.nix-profile/share/terminfo
        # source system wide zshrc, for nix configuration if it exists
        # so that the nix profile variables get set (e.g. NIX_REMOTE)
        # (this might be MacOS/"Darwin" specific, or also work the same way other linux distributions)
        [ -f /etc/zshrc ] && source /etc/zshrc
      fi
      
      # Added by Toolbox App
      export PATH="$PATH:/Users/${vars.user}/Library/Application Support/JetBrains/Toolbox/scripts"

      export PATH="$PATH:/etc/profiles/per-user/${vars.user}/bin:/Users/${vars.user}/.node_modules/bin:/sbin:$HOME/.rd/bin:/nix/var/nix/profiles/default/bin"
      export PATH="/opt/homebrew/opt/bison/bin:$PATH"
      export PATH="$HOME/.local/bin:$PATH"
      export PNPM_HOME="$HOME/.local/share/pnpm"
      export PATH="$PNPM_HOME:$PATH"
      source $HOME/.sde/profile/profile.sh

      export NODE_EXTRA_CA_CERTS="$HOME/ca-certs/certs/combined_ca.pem"
      
      eval "$(/opt/homebrew/bin/brew shellenv)"
      [ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"

      export SDKMAN_DIR="$HOME/.sdkman"
      source "$SDKMAN_DIR/bin/sdkman-init.sh"

      ## END NIX
      ## The previous part of this ZSHRC is generated by nix and configured in ~/.config/nixpkgs/zsh/zsh.nix
      ## The following part of this  ZSHRC is read from ~/.config/nixpkgs/zsh/zshrc

      ${builtins.readFile ./zshrc}
    '';

    # profileExtra = ''
    #   export PATH="$HOME/scripts:$HOME/bin:/opt/local/bin:/usr/local/bin:/Users/wrose/Library/Application Support/Coursier/bin:/bin:/usr/bin:/run/current-system/sw/bin:$HOME/.sxm/bin"
    #
    #
    #   # set TERMINFO to the terminfos delivered by the ncurses nix package
    #   if [ ! -f /etc/NIXOS ]; then
    #     export TERMINFO=$HOME/.nix-profile/share/terminfo
    #     # source system wide zshrc, for nix configuration if it exists
    #     # so that the nix profile variables get set (e.g. NIX_REMOTE)
    #     # (this might be MacOS/"Darwin" specific, or also work the same way other linux distributions)
    #     [ -f /etc/zshrc ] && source /etc/zshrc
    #   fi
    #   
    #   # Added by Toolbox App
    #   export PATH="$PATH:/Users/${vars.user}/Library/Application Support/JetBrains/Toolbox/scripts"
    #
    #   export PATH="$PATH:/etc/profiles/per-user/${vars.user}/bin:/Users/${vars.user}/.node_modules/bin:/sbin:$HOME/.rd/bin:/nix/var/nix/profiles/default/bin"
    #   export PATH="/opt/homebrew/opt/bison/bin:$PATH"
    #   export PATH="$HOME/.local/bin:$PATH"
    #   source $HOME/.sde/profile/profile.sh
    #
    #   export NODE_EXTRA_CA_CERTS="$HOME/ca-certs/certs/combined_ca.pem"
    #   
    #   eval "$(/opt/homebrew/bin/brew shellenv)"
    #   [ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"
    #
    # '';
  };
}
