{ pkgs, vars, config, ... }: {
  programs.zsh = {
    enable = true;

    enableCompletion = true;
    # autosuggestion = {
    #   enable = true;
    # };
    #shellAliases = import ../bash/aliases.nix;
    shellAliases = {
      l = "ls -Glah";
      nixswitch = "sudo darwin-rebuild switch --flake ~/.dotfiles#$(hostname -s)";
      nixup = "pushd ~/.dotfiles; nix flake update; nixswitch; popd";
      sbtc = "sbt --client";

      # Email aliases
      mailsync = "~/.local/bin/offlineimap-sync && notmuch new";
      mail = "neomutt";
      refresh-bridge-cert = "~/.dotfiles/scripts/refresh-bridge-cert.sh";
      mailsearch = "notmuch search";
      mailcount = "notmuch count";
      maillogs = "tail -f ~/Library/Logs/offlineimap.log";
    };
    history = {
      ignoreDups = true;
      share = true;
      save = 100000;
    };

    oh-my-zsh = {
      enable = true;
      plugins = [ "dircycle" "zsh-navigation-tools" "ssh-agent" "z" ];
      /* ugly hack: oh my zsh only wants a relative path, so lets go back to the system root */
      #theme = "robbyrussell";
      #theme = "../../../../../../../../../../../${pkgs.zsh-powerlevel9k}/share/zsh-powerlevel9k/powerlevel9k";
      extraConfig = ''
        zstyle :omz:plugins:ssh-agent identities id_ed25519
      '';
    };

    sessionVariables = config.home.sessionVariables;

    initContent = ''
      # Load secrets as environment variables
      [ -r "${config.sops.secrets.localstack_auth_token.path}" ] && export LOCALSTACK_AUTH_TOKEN="$(cat ${config.sops.secrets.localstack_auth_token.path})"
      [ -r "${config.sops.secrets.ghe_token.path}" ] && export GITHUB_API_TOKEN="$(cat ${config.sops.secrets.ghe_token.path})"
      [ -r "${config.sops.secrets.jira_personal_token.path}" ] && export JIRA_PERSONAL_TOKEN="$(cat ${config.sops.secrets.jira_personal_token.path})"
      [ -r "${config.sops.secrets.jira_username.path}" ] && export JIRA_USERNAME="$(cat ${config.sops.secrets.jira_username.path})"
      [ -r "${config.sops.secrets.confluence_personal_token.path}" ] && export CONFLUENCE_PERSONAL_TOKEN="$(cat ${config.sops.secrets.confluence_personal_token.path})"

      export PATH="$HOME/scripts:$HOME/bin:/usr/sbin:/opt/local/bin:/usr/local/bin:/Users/wrose/Library/Application Support/Coursier/bin:/bin:/usr/bin:/run/current-system/sw/bin:$HOME/.sxm/bin"

      export NVM_DIR="$HOME/.nvm"
      [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm

      # set TERMINFO to the terminfos delivered by the ncurses nix package
      if [ ! -f /etc/NIXOS ]; then
        export TERMINFO=$HOME/.nix-profile/share/terminfo
        # source system wide zshrc, for nix configuration if it exists
        # so that the nix profile variables get set (e.g. NIX_REMOTE)
        # (this might be MacOS/"Darwin" specific, or also work the same way other linux distributions)
        [ -f /etc/zshrc ] && source /etc/zshrc
      fi
      
      # Added by Toolbox App
      export PATH="$PATH:/Users/${vars.user}/Library/Application Support/JetBrains/Toolbox/scripts"

      export PATH="$PATH:/etc/profiles/per-user/${vars.user}/bin:/Users/${vars.user}/.node_modules/bin:/sbin:$HOME/.rd/bin:/nix/var/nix/profiles/default/bin"
      export PATH="/opt/homebrew/opt/bison/bin:$PATH"
      export PATH="$HOME/.local/bin:$PATH"
      export PNPM_HOME="$HOME/.local/share/pnpm"
      export PATH="$PNPM_HOME:$PATH"

      export ENABLE_TOOL_SEARCH=true 
      export NODE_EXTRA_CA_CERTS="$HOME/ca-certs/certs/combined_ca.pem"
      export JIRA_URL=https://jira.savagebeast.com
      
      eval "$(/opt/homebrew/bin/brew shellenv)"
      [ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"

      # SDKMAN owns the JDKs (and any other JVM candidates). It is deliberately
      # not nix-managed: it self-updates and installs into ~/.sdkman, so there
      # is nothing sensible for nix to pin. Guarded so a machine that has not
      # run the SDKMAN installer yet still gets a working shell.
      #
      # sdkman-init.sh puts the current candidate on PATH *and* exports
      # JAVA_HOME, overriding whatever was already set -- so no explicit PATH
      # prepend is needed here, and `sdk use java <ver>` correctly moves both.
      export SDKMAN_DIR="$HOME/.sdkman"
      [ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

      ## END NIX
      ## The previous part of this ZSHRC is generated by nix and configured in ~/.config/nixpkgs/zsh/zsh.nix
      ## The following part of this  ZSHRC is read from ~/.config/nixpkgs/zsh/zshrc

      ${builtins.readFile ./zshrc}
    '';

    # Generates ~/.zprofile. Adopted from a hand-written ~/.zprofile that was
    # sitting outside nix; home-manager moves that original aside as
    # ~/.zprofile.backup on first activation (backupFileExtension = "backup").
    #
    # JAVA_HOME points at SDKMAN's 'current' symlink rather than resolving a
    # specific JDK via /usr/libexec/java_home, so that `sdk default java <ver>`
    # is the single place a JDK gets chosen. Two reasons it is set here at all,
    # rather than left entirely to sdkman-init.sh:
    #
    #   1. sdkman-init.sh only runs in interactive shells (it is sourced from
    #      initExtra / .zshrc). Setting it in .zprofile covers login shells and
    #      anything that inherits their environment.
    #   2. It cannot disagree with sdkman: both resolve to the same 'current'
    #      symlink. A per-shell `sdk use java <ver>` still wins, because
    #      sdkman-init.sh re-exports JAVA_HOME on top of this.
    #
    # Ordering note: home-manager/zshrc sources ~/.zprofile *from* .zshrc,
    # after sdkman-init.sh has run. That is why the previous java_home pin
    # silently beat sdkman -- PATH resolved to sdkman's java while JAVA_HOME
    # pointed at a brew JDK. Pointing both at 'current' removes the conflict.
    #
    # The -d guard keeps JAVA_HOME unset (rather than dangling) on a machine
    # where SDKMAN has no java candidate installed yet.
    #
    # brew shellenv also runs in initExtra. That duplication predates this
    # block and is kept deliberately: login shells need it here, and dropping
    # it from either place would change PATH ordering.
    profileExtra = ''
      eval "$(/opt/homebrew/bin/brew shellenv zsh)"
      if [ -d "$HOME/.sdkman/candidates/java/current" ]; then
        export JAVA_HOME="$HOME/.sdkman/candidates/java/current"
      fi
      export M2_HOME=/opt/homebrew/opt/maven/libexec
    '';

    # Historical, kept for reference:
    # profileExtra = ''
    #   export PATH="$HOME/scripts:$HOME/bin:/opt/local/bin:/usr/local/bin:/Users/wrose/Library/Application Support/Coursier/bin:/bin:/usr/bin:/run/current-system/sw/bin:$HOME/.sxm/bin"
    #
    #
    #   # set TERMINFO to the terminfos delivered by the ncurses nix package
    #   if [ ! -f /etc/NIXOS ]; then
    #     export TERMINFO=$HOME/.nix-profile/share/terminfo
    #     # source system wide zshrc, for nix configuration if it exists
    #     # so that the nix profile variables get set (e.g. NIX_REMOTE)
    #     # (this might be MacOS/"Darwin" specific, or also work the same way other linux distributions)
    #     [ -f /etc/zshrc ] && source /etc/zshrc
    #   fi
    #   
    #   # Added by Toolbox App
    #   export PATH="$PATH:/Users/${vars.user}/Library/Application Support/JetBrains/Toolbox/scripts"
    #
    #   export PATH="$PATH:/etc/profiles/per-user/${vars.user}/bin:/Users/${vars.user}/.node_modules/bin:/sbin:$HOME/.rd/bin:/nix/var/nix/profiles/default/bin"
    #   export PATH="/opt/homebrew/opt/bison/bin:$PATH"
    #   export PATH="$HOME/.local/bin:$PATH"
    #
    #   export NODE_EXTRA_CA_CERTS="$HOME/ca-certs/certs/combined_ca.pem"
    #   
    #   eval "$(/opt/homebrew/bin/brew shellenv)"
    #   [ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"
    #
    # '';
  };
}
